### ISSUE TITLE
Error just importing.

### ISSUE THREAD

**Issue by sneckelmann** [bonjurmrfirst/angular4-carousel#31]
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

I've installed the package (npm i --save angular4-carousel) and then import the CarouselModule to app.module as well as add the **import { CarouselModule } from 'angular4-carousel';** line.

I get this error:
`ERROR in ./node_modules/angular4-carousel/index.ts
Module build failed: Error: ~~~\node_modules\angular4-carousel\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (~~~\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (~~~\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 14:0-51
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts`

Any ideas what I'm doing wrong?

**Comment by sneckelmann** [comment]
Seems to be related to this issue.  https://github.com/angular/angular-cli/issues/8284

**Comment by SureshNatarajan** [comment]
Hi @bonjurmrfirst,

Build fails with angular cli v1.5.0 and above. Do we have a resolution for this issue in any of the latest versions ?
