### ISSUE TITLE
Angular4-carousel is not working with angular 5

### ISSUE THREAD

**Issue by heena22626** [bonjurmrfirst/angular4-carousel#34]
I'm stuck here, and i need to use slider in my angular5 project but while running the server after installing carousel its throwing error:

ERROR in ./node_modules/angular4-carousel/index.ts
Module build failed: Error: D:\Workspace\ntwine\node_modules\angular4-carousel\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (D:\Workspace\ntwine\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:649:23)
    at plugin.done.then (D:\Workspace\ntwine\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/app.module.ts 12:0-51
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by ArthurBrito** [comment]
Having the same problem

**Comment by rajautsav** [comment]
I'm having the same issue.

**Comment by ing4prg** [comment]
Any idea when an update will be ready?

**Comment by GabeAboy** [comment]
Seriously can we get this?

**Comment by dtarasenko** [comment]
The same issue. Any workaround? Thanks

**Comment by heena22626** [comment]
Yes, for now i'm using ngx-carousel, and it works for me pretty well.

**Comment by hemanthsp** [comment]
ngx-carousel doesnot support in finite loop
