### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by saxenaamanraj193** [bonjurmrfirst/angular4-carousel#41]
ERROR in ./node_modules/angular4-carousel/index.ts
Module build failed: Error: /home/sneha/Desktop/projects/mentorzweb/node_modules/angular4-carousel/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/sneha/Desktop/projects/mentorzweb/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:709:23)
    at plugin.done.then (/home/sneha/Desktop/projects/mentorzweb/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by raedwulf1** [comment]
Same Error Here!

**Comment by Aravindsaiv** [comment]
Got the same error. Any resolutions?
